# Generated by Django 5.2.7 on 2025-10-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='link_backend',
            field=models.URLField(blank=True),
        ),
    ]
