# Generated by Django 5.2.7 on 2025-10-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_resource_link_resource_link_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link_backend',
            field=models.CharField(blank=True),
        ),
    ]
