# Generated by Django 5.2.7 on 2025-10-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_gps_latitude_user_gps_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='link',
            new_name='link_frontend',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='key',
        ),
        migrations.AddField(
            model_name='resource',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_connection',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
