# Generated by Django 5.2.7 on 2025-10-30 19:41

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('CONFIRMADO', 'Confirmado (en zona)'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado (no llegó a tiempo)'), ('OCUPADO', 'Ocupado (ruta de regreso)')], default='RESERVADO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('cancelado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cupo',
                'verbose_name_plural': 'Cupos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posicion', models.PositiveIntegerField(help_text='Posición en la lista de espera.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignado', models.BooleanField(default=False, help_text='Si el usuario fue promovido a cupo.')),
            ],
            options={
                'verbose_name': 'Lista de espera',
                'verbose_name_plural': 'Listas de espera',
                'ordering': ['posicion'],
            },
        ),
        migrations.CreateModel(
            name='LlenadoRuta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático')], default='AUTOMATICO', max_length=20)),
                ('cupos_ocupados', models.PositiveIntegerField(default=0)),
                ('total_cupos', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Llenado de ruta',
                'verbose_name_plural': 'Llenados de rutas',
                'ordering': ['-fecha'],
            },
        ),
    ]
