# Generated by Django 5.2.7 on 2025-10-31 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cupos', '0001_initial'),
        ('rutas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cupo',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos', to='rutas.ruta'),
        ),
        migrations.AddField(
            model_name='cupo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_espera', to='rutas.ruta'),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_espera', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llenadoruta',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llenados_reportados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llenadoruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llenados', to='rutas.ruta'),
        ),
        migrations.AlterUniqueTogether(
            name='cupo',
            unique_together={('usuario', 'ruta')},
        ),
        migrations.AlterUniqueTogether(
            name='listaespera',
            unique_together={('usuario', 'ruta')},
        ),
    ]
