# Generated by Django 5.2.7 on 2025-10-31 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupo',
            name='activo',
        ),
    ]
