# Generated by Django 5.2.7 on 2025-10-31 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupos', '0003_remove_cupo_activo'),
        ('rutas', '0002_alter_desvio_options_alter_ruta_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cupo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cupo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cupo',
            name='expirado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cupo',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupos', to='rutas.horarioruta'),
        ),
        migrations.AlterUniqueTogether(
            name='cupo',
            unique_together={('usuario', 'ruta', 'horario')},
        ),
    ]
