# Generated by Django 5.2.7 on 2025-10-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupos', '0004_alter_cupo_unique_together_cupo_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupo',
            name='es_lista_espera',
            field=models.BooleanField(default=False, help_text='Indica si este cupo fue tomado como lista de espera automática.'),
        ),
        migrations.DeleteModel(
            name='ListaEspera',
        ),
    ]
