# Generated by Django 5.2.7 on 2025-10-31 03:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paradas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(help_text='Placa o identificación del vehículo.', max_length=20, unique=True)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('capacidad', models.PositiveIntegerField(default=40, help_text='Capacidad total de pasajeros.')),
                ('activo', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='BusRuta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_rutas', to='rutas.bus')),
            ],
            options={
                'verbose_name': 'Asignación de bus a ruta',
                'verbose_name_plural': 'Asignaciones bus-ruta',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('ciudad', 'desde la universidad, hacia la ciudad'), ('fuera de la ciudad', 'desde la universidad, hacia municipios cercanos')], default='ciudad', max_length=20)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
                ('capacidad_total', models.PositiveIntegerField(default=40)),
                ('capacidad_espera', models.PositiveIntegerField(default=10)),
                ('hora_salida', models.TimeField()),
                ('hora_llegada_estimada', models.TimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('buses', models.ManyToManyField(related_name='rutas', through='rutas.BusRuta', to='rutas.bus')),
                ('conductor', models.ForeignKey(help_text='Conductor responsable principal de la ruta.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta universitaria',
                'verbose_name_plural': 'Rutas universitarias',
                'ordering': ['hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='HistorialRuta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_ruta', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Evento de ruta',
                'verbose_name_plural': 'Historial de rutas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Desvio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Motivo o detalle del desvío.')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desvios_registrados', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desvios', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Desvío',
                'verbose_name_plural': 'Desvíos',
                'ordering': ['-inicio'],
            },
        ),
        migrations.AddField(
            model_name='busruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_rutas', to='rutas.ruta'),
        ),
        migrations.AlterUniqueTogether(
            name='busruta',
            unique_together={('bus', 'ruta')},
        ),
        migrations.CreateModel(
            name='RutaParada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField(help_text='Orden de paso en la ruta.')),
                ('tiempo_estimado', models.DurationField(blank=True, help_text='Tiempo estimado desde el inicio.', null=True)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas_rutas', to='paradas.parada')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_paradas', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Parada en ruta',
                'verbose_name_plural': 'Paradas por ruta',
                'ordering': ['orden'],
                'unique_together': {('ruta', 'parada')},
            },
        ),
    ]
