# Generated by Django 5.2.7 on 2025-10-30 19:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paradas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('IDA', 'Ida (desde la universidad)'), ('REGRESO', 'Regreso (hacia la universidad)')], default='IDA', max_length=20)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
                ('vehiculo', models.CharField(help_text='Identificación o placa del vehículo asignado.', max_length=50)),
                ('capacidad_total', models.PositiveIntegerField(default=40)),
                ('capacidad_espera', models.PositiveIntegerField(default=10)),
                ('hora_salida', models.DateTimeField()),
                ('hora_llegada_estimada', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(help_text='Usuario asignado como conductor principal.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta universitaria',
                'verbose_name_plural': 'Rutas universitarias',
                'ordering': ['hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='HistorialRuta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_ruta', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Evento de ruta',
                'verbose_name_plural': 'Historial de rutas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Desvio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Motivo o detalle del desvío.')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desvios_registrados', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desvios', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Desvío',
                'verbose_name_plural': 'Desvíos',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='RutaParada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField(help_text='Orden de paso en la ruta.')),
                ('tiempo_estimado', models.DurationField(blank=True, help_text='Tiempo estimado desde el inicio.', null=True)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas_rutas', to='paradas.parada')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_paradas', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Parada en ruta',
                'verbose_name_plural': 'Paradas por ruta',
                'ordering': ['orden'],
                'unique_together': {('ruta', 'parada')},
            },
        ),
    ]
