# Generated by Django 5.2.7 on 2025-10-31 04:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desvio',
            options={'ordering': ['-inicio'], 'verbose_name': 'Desvío detectado', 'verbose_name_plural': 'Desvíos detectados'},
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['nombre'], 'verbose_name': 'Ruta universitaria', 'verbose_name_plural': 'Rutas universitarias'},
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='hora_llegada_estimada',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='hora_salida',
        ),
        migrations.AddField(
            model_name='desvio',
            name='detectado_automaticamente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='desvio',
            name='distancia_desviacion',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Distancia máxima fuera de ruta (en metros).', max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desvio',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Solo si se registra manualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desvios_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='desvio',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Detalle del desvío detectado automáticamente.'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='tipo',
            field=models.CharField(choices=[('ciudad', 'Desde la universidad hacia la ciudad'), ('fuera_de_la_ciudad', 'Desde la universidad hacia municipios cercanos')], default='ciudad', max_length=30),
        ),
        migrations.CreateModel(
            name='HorarioRuta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hora_salida', models.TimeField()),
                ('hora_llegada_estimada', models.TimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el horario está actualmente vigente.')),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Horario de ruta',
                'verbose_name_plural': 'Horarios de ruta',
                'ordering': ['hora_salida'],
            },
        ),
        migrations.AddField(
            model_name='desvio',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desvios', to='rutas.horarioruta'),
        ),
    ]
