# Generated by Django 5.2.7 on 2025-10-31 03:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origen_tipo', models.CharField(choices=[('USUARIO', 'Usuario'), ('VEHICULO', 'Vehículo')], max_length=20)),
                ('origen_id', models.UUIDField(help_text='UUID del usuario o vehículo asociado.')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('precision', models.DecimalField(blank=True, decimal_places=2, help_text='Precisión del GPS en metros.', max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FUERA_DE_RANGO', 'Fuera de rango'), ('SIN_SEÑAL', 'Sin señal'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Posición GPS',
                'verbose_name_plural': 'Posiciones GPS',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('distancia_recorrida_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duracion_total', models.DurationField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trayecto GPS',
                'verbose_name_plural': 'Trayectos GPS',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AlertaGPS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(help_text='Tipo de alerta (sin señal, desvío, fuera de zona, etc.)', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('detectada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('resuelta', models.BooleanField(default=False)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta GPS',
                'verbose_name_plural': 'Alertas GPS',
                'ordering': ['-detectada_en'],
            },
        ),
    ]
