# Generated by Django 5.2.7 on 2025-10-30 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gps', '0001_initial'),
        ('rutas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertagps',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_gps', to='rutas.ruta'),
        ),
        migrations.AddField(
            model_name='posicion',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posiciones', to='rutas.ruta'),
        ),
        migrations.AddField(
            model_name='alertagps',
            name='posicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='gps.posicion'),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trayectos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trayectos', to='rutas.ruta'),
        ),
    ]
