# Generated by Django 5.2.7 on 2025-10-30 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paradas', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='rutas',
            field=models.ManyToManyField(related_name='paradas', through='rutas.RutaParada', to='rutas.ruta'),
        ),
        migrations.AddField(
            model_name='parada',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paradas', to='paradas.zonaparada'),
        ),
        migrations.AlterUniqueTogether(
            name='parada',
            unique_together={('latitud', 'longitud')},
        ),
    ]
